name = "discover-competition"
main = "src/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 * * * *"]

[[kv_namespaces]]
binding = "COMPETITION_KV"
id = "7fee0107eb3746e9b595888b802b9a9b"

[vars]
TARGET_URL = "https://www.competehub.dev/zh/competitions?page=1&sort=recently-launched"
COMPETITION_PAGE_BASE = "https://www.competehub.dev/competitions/"

[observability]
enabled = true
